### ISSUE TITLE
how to use responsive prefixes?

### ISSUE THREAD

**Issue by kepi0809** [ky-is/vue-cli-plugin-tailwind#1]
Sorry this is maybe a stupid question, but I couldn't figure out it on my own yet, and couldn't find anything about it online. 

So what I want to do is to make responsive prefixes (for example: sm:classname md:classname etc.)

Thanks for you help in advance. 👍

**Comment by ky-is** [comment]
Sounds like https://tailwindcss.com/docs/functions-and-directives/#responsive is what you're looking for, if you didn't see that already. (I believe `@variants responsive` and `@responsive` do the same thing.)
