### ISSUE TITLE
Rule conflict with Airbnb "'tailwindcss' should be listed in the project's dependencies. Run 'npm i -S tailwindcss' to add it"

### ISSUE THREAD

**Issue by lloydjatkinson** [ky-is/vue-cli-plugin-tailwind#10]
```js
const { colors } = require('tailwindcss/defaultTheme');

module.exports = {
    theme: {
        extend: {
            colors: {
                'hn-orange': '#ff6600',
            },
        },
    },
};
```

`'tailwindcss' should be listed in the project's dependencies. Run 'npm i -S tailwindcss' to add it`

It's not clear exactly is wrong here. Does vue-cli-plugin-tailwind forget to install tailwindcss too or is it by design that we need to also add that?

**Comment by TotomInc** [comment]
According to ESLint, when you `require` a module in your project, the required module must be listed in the project dependencies, whatever if you are requiring a module in a config file or not.

There is also the same error when [working on Electron apps](https://stackoverflow.com/a/50803712/8073629) (where it is recommended to keep Electron as a dev-dependency).

I would recommend turning off the `import/no-extraneous-dependencies` rule.
