### ISSUE TITLE
[Compatibility issue] PurgeCSS kicks in too often

### ISSUE THREAD

**Issue by OwenMelbz** [ky-is/vue-cli-plugin-tailwind#3]
Hi,

We'd been having a problem with Storybook and using your tailwind project by where on the initial running of the tool all css would work.

Then as we added new classes onto elements, the styling never applied, and the source code never had class in it.

We assumed this was to do with the purge.

Checking out the `postcss.config.js` we noticed

```
const isHotReloaded = process.argv.includes('serve')
```

This would then run purge.

This is pretty problematic when interfacing with other tools that do not pass in a `serve` argument.

Typically you'd only run that process when the `NODE_ENV` is set to production that way all the tools stay in sync.

I've submitted a PR with a potential change if you're interested :)

**Comment by ky-is** [comment]
Thank you for the fix!
