### ISSUE TITLE
IDE Autocomplete Support

### ISSUE THREAD

**Issue by tylergets** [ky-is/vue-cli-plugin-tailwind#5]
Hey I love the plugin, posting this issue to maybe get some insight from other users. I am trying to find a way to add IDE auto complete via this plugin, when using tailwind vanilla in vue I just generate a tailwind.css file (or download from CDN) and just leave it in the root for my IDE to pick up. Wondering if anyone has another solution

**Comment by ky-is** [comment]
I haven't tried this before so I'm not sure... Does your technique for vanilla Vue not work here? Or you're wondering if this functionality could be included out of the box by the plugin?

**Comment by tylergets** [comment]
It works, however it would be nice to include this out of the box. I'd be willing to help write the support, just not sure the best way to go about it.

**Comment by ky-is** [comment]
What IDE are you using? In VSCode I use https://github.com/bradlc/vscode-tailwindcss for autocompletion. I'm a little hesitant to include this extra file with every installation. Maybe some how-tos in the readme on enabling autocompletion is the way to go.

**Comment by tylergets** [comment]
I'm using intellij/webstorm.

I understand your hesitation, the problem is more general than this
specific plugin. (how to get an ide to recognize the postcss directives
declared inside Vue style tags)

However because I don't think many users are going to be using tailwind +
other postcss it might be within scope.

**Comment by tylergets** [comment]
If declared within scope, we should generate the css file at runtime, not
just include it as the tailwind variables might change

**Comment by ky-is** [comment]
If there's a way to do this that works generically with a range of IDEs, then I'm very open to a pull request. I don't have a strong enough personal incentive to implement it myself at this point. May reevaluate that after Tailwind 1.0 and vue-cli 4.0. Thanks for bringing this up for discussion!

**Comment by mikeerickson** [comment]
I use PHPStorm for all PHP work, otherwise VSCode.  I would love to have this functionality. I am going to be installing this new version into a new Vue project next week.

**Comment by ky-is** [comment]
Closing for now as I don't know of a global solution or have a plan to implement. See also: https://github.com/tailwindcss/discuss/issues/55.
