### ISSUE TITLE
postcss-purgecss remove components styling imported from the node_modules

### ISSUE THREAD

**Issue by TotomInc** [ky-is/vue-cli-plugin-tailwind#6]
It looks like the configuration of the `@fullhuman/postcss-purgecss` plugin in `postcss.config.js` remove the style used from `node_modules` components such as Epic Spinners or Vue Good Table.

For example, my production build doesn't have the styling of the table plugin ([Vue Good Table](https://xaksis.github.io/vue-good-table/)). I removed a bit of the code generated by this vue-plugin in `postcss.config.js` and it worked well after, both in development and production:

```javascript
/* eslint "global-require": "off" */
/* eslint "import/no-extraneous-dependencies": "off" */
const IN_PRODUCTION = process.env.NODE_ENV === 'production';

class TailwindVueExtractor {
  static extract(content) {
    const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '');
    return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_:/]+/g) || [];
  }
}

const extensionsUsingCSS = ['vue', 'html'];
const extensionsOfCSS = ['css', 'less', 'pcss', 'postcss', 'sass', 'scss', 'styl'];

module.exports = {
  plugins: [
    require('postcss-preset-env')({ stage: 2 }),
    require('tailwindcss')('./tailwind.config.js'),
    // IN_PRODUCTION && require('@fullhuman/postcss-purgecss')({
    //   content: [`./@(public|src)/**/*.@(${extensionsUsingCSS.join('|')})`],
    //   css: [`./src/**/*.@(${extensionsOfCSS.join('|')})`],
    //   extractors: [
    //     {
    //       extractor: TailwindVueExtractor,
    //       extensions: extensionsUsingCSS,
    //     },
    //   ],
    //   whitelist: [],
    //   whitelistPatterns: [/-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^router-link(|-exact)-active$/],
    // }),
    require('autoprefixer')(),
  ],
};
```

**Comment by ky-is** [comment]
There is no one-size fits all approach to purging CSS classes, since each project will have different structures and external CSS sources. If PurgeCSS can't find a file that's consuming CSS you depend on, it's going to purge those styles.

You can remove PurgeCSS if you don't mind your CSS output being much larger (at which point you should just include TailwindCSS from a CDN). A better approach is to add any styled 3rd party libraries to PurgeCSS's search paths.

Add `vue-good-table`'s source `.vue` files to your config's `content` list:
```js
      content: [ `./@(public|src)/**/*.@(${extensionsUsingCSS.join('|')})`, `./node_modules/vue-good-table/src/**/*.vue` ],
```

Of course, you could just include every folder in `node_modules` in the scan and it would work more generically, but in a project with many dependencies, that could catch false positives and add minutes to your build time, so I don't think that's an acceptable default.

Let me know if that helps!

**Comment by TotomInc** [comment]
I'm pretty new to the whole postcss-plugins thing and haven't really tried to configurate any postcss-plugin. I will take a deeper look at the most appropriate production configuration with tailwindcss with what you said.

However, since it is a bug that is related to the configuration when @ky-is/vue-cli-plugin-tailwind is invoked, is it possible to mention it in the docs/readme? Maybe that would help other people who have a broken production build.

EDIT: also will you update the plugin when 1.0.0 of tailwindcss will be released?

**Comment by ky-is** [comment]
Assuming that's the only 3rd party CSS in your app, the only change you need to make to the configuration is adding that one entry (`'./node_modules/vue-good-table/src/**/*.vue'` to the `content` array of search paths. I do recommend looking at PurgeCSS enough to understand what that does, but a quick look at their docs should cover that.

It's not really a bug related to this plugin. PurgeCSS requires configuration, and this plugin can only provide a default that covers the use cases it knows about (i.e. Vue's autogenerated classes, and the classes you explicitly consume in your single-file components). Handling 3rd party CSS is mentioned in the `Configuration` section of the readme, but it should be made clearer, and probably include an example (hence leaving this issue open with the `needs documentation` label).

One possible approach I can think to avoid searching all of `node_modules` of would be to compile a list of popular Vue libraries that do require importing CSS and include them in the plugin's search patterns by default. That's wouldn't be a perfect fix, and is way beyond my scope for this project, but pull requests and opening issues for proposals are always welcome.

**Comment by ky-is** [comment]
I'll release 2.0.0 of this plugin when Tailwind reaches 1.0. Frankly I thought that would happen quite a bit faster so it wouldn't be worth making a beta of this plugin. I pushed my local changes to GitHub now.

**Comment by TotomInc** [comment]
> One possible approach I can think to avoid searching all of node_modules of would be to compile a list of popular Vue libraries that do require importing CSS and include them in the plugin's search patterns by default.

IMO, that's way too much work and requires a lot of maintenance, that's something to avoid.

Maybe there is a smarter way to find external CSS from librairies injected at build time, I'll try to investigate that when I have some time...

If the plugin configuration can't adapt for every project (which is absolutely normal), we should make it clearer in the docs about handling CSS from external libraires.

**Comment by ky-is** [comment]
The documentation has been updated in 811eb095e3434746c94ff7c00aeab3a4097e8f60, thanks for bringing this up!
