### ISSUE TITLE
Build fails with beta 1

### ISSUE THREAD

**Issue by Uninen** [ky-is/vue-cli-plugin-tailwind#7]
First, Thank You for this awesome piece of software! 👍 

After upgrading to beta 1 my builds fail but dev env works normally. When I copied the [old postcss config](https://github.com/ky-is/vue-cli-plugin-tailwind/blob/d20eee7b7b29753e11c32b87bf492070f08ec021/generator/templates/postcss.config.js) back, everything works again.

```error  in ./src/assets/styles/tailwind.postcss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: The extractor has failed to extract the selectors.
[...] 
 @ ./src/main.js 8:0-42
 @ multi ./src/main.js
```

I'm using mainly SASS in my .vue files (indented syntax) and just one `.postcss` file that is imported in `main.js`. Latest vue-cli, latest everything basically. Don't really see where the actual problem is, but as the build works with the older config file it works as a workaround for me for now.

**Comment by ky-is** [comment]
Thanks for the report! This looks like a regression from removing the empty array fallback from the extractor. That could choke on a blank file.

Try making this change and see if that fixes it: https://github.com/ky-is/vue-cli-plugin-tailwind/commit/4767d80a2c12a7f66c403de06d83112d33d5de96

**Comment by ky-is** [comment]
https://github.com/ky-is/vue-cli-plugin-tailwind/releases/tag/v2.0.0-beta.2 is live with this fix. If you're still having any troubles let me know, thank you!

**Comment by Uninen** [comment]
This indeed fixes the issue. Thank You! 👍
