### ISSUE TITLE
Comparison with forsartis/vue-cli-plugin-tailwind

### ISSUE THREAD

**Issue by franciscolourenco** [ky-is/vue-cli-plugin-tailwind#8]
Hi, found your plugin via https://medium.com/@kyis/vue-tailwind-purgecss-the-right-way-c70d04461475

Are you aware of differences (beside documentation) between this plugin and https://medium.com/@kyis/vue-tailwind-purgecss-the-right-way-c70d04461475 ?

Thanks!

**Comment by ky-is** [comment]
Hi! I haven't tried that plugin personally, but we can check its configuration https://github.com/forsartis/vue-cli-plugin-tailwind/blob/master/purgecss/index.js. Out of the box, it looks like it doesn't currently support:
- Vue's class binding object syntax (unless you're careful to always wrap keys in quotation marks)
- Purging single-file components with `<style>` blocks (not a big deal, just can cause a slightly larger than necessary output size)
- `<transition>` / `<transition-group>` animations
- Styling vue-router's `<router-link>` custom classes

As long as you make the changes listed in the article to its configuration after installing it (for the features you care about) then it should be fine to use. But at that point I'd probably just do it from scratch in your PostCSS config. Let me know if you have any other questions, thanks!
