### ISSUE TITLE
Adding custom CSS

### ISSUE THREAD

**Issue by dewdad** [ky-is/vue-cli-plugin-tailwind#9]
As per the Tailwind docs I'm trying to add some heading theming between 
```@import '~tailwindcss/base.css';```
and 
```@import '~tailwindcss/components.css';```

Something like this:
```css
// custom.css
h1 {
  @apply text-2xl;
}
h2 {
  @apply text-xl;
}
h3 {
  @apply text-lg;
}
a {
  @apply text-blue-600 underline;
}
```

Tried inlining and also importing the file from the styles ( tailwind.postcss parent) directory which did not work. What should I be doing here?

**Comment by ky-is** [comment]
You may need to use `!important` as the CSS specificity for these base selectors is very low, and may get overridden somewhere. Otherwise post how you're including custom.css and I'll take a look, thanks!

**Comment by franciscolourenco** [comment]
I'm having the same problem with non-class selectors. All the css applied to element selectors is being purged.

**Comment by franciscolourenco** [comment]
@ky-is nevermind, it is the removal of <style> blocks from vue components. I'm using some dynamic classes, and before I was using the other plugin which whitelists everything inside vue files.
